name: Single Runner
'on':
  workflow_dispatch:
    inputs:
      EC2_INSTANCE_TYPE:
        description: 'EC2 instance type (ex: t3.micro or t3.medium)'
        required: true
        default: 'c6a.4xlarge'
      EC2_TARGET_SIZE:
        description: Storage allocated to the machine (in GB)
        required: true
        type: string
        default: '30'
      EXPERIMENT_ID:
        description: Experiment ID (to identify the run in S3)
        required: true
        type: string
      DATE_EXECUTION_SUBFOLDER_BOOL:
        description: 'Put the output in a execution date subfolder (ex: 27/06/2023_10:30:45_UTC/)'
        required: true
        type: boolean
        default: true
      EC2_INSTANCE_TYPE_SUBFOLDER_BOOL:
        description: 'Put the output in a EC2 instance type folder (ex: m5a.xlarge/)'
        required: true
        type: boolean
        default: true
      PIPELINE:
        type : choice
        description: Pipeline to run
        required: true
        options: 
        - main
permissions: write-all
concurrency: 
  # Only one workflow per pipeline per experiment_id is allowed to run at a time in the repository
  group: single_runner_${{github.event.inputs.PIPELINE}}_${{github.event.inputs.EXPERIMENT_ID}}
jobs:
  main:
    if: github.event.inputs.PIPELINE == 'main'
    uses: ./.github/workflows/main.yaml
    with:
      EC2_INSTANCE_TYPE: ${{ github.event.inputs.EC2_INSTANCE_TYPE }}
      EC2_TARGET_SIZE: ${{ github.event.inputs.EC2_TARGET_SIZE }}
      EXPERIMENT_ID: ${{ github.event.inputs.EXPERIMENT_ID }}
      DATE_EXECUTION_SUBFOLDER_BOOL: ${{github.event.inputs.DATE_EXECUTION_SUBFOLDER_BOOL}}
      EC2_INSTANCE_TYPE_SUBFOLDER_BOOL: ${{github.event.inputs.EC2_INSTANCE_TYPE_SUBFOLDER_BOOL}}
    secrets:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
