name: Single Runner
'on':
  workflow_dispatch:
    inputs:
      EC2_INSTANCE_TYPE:
        description: 'EC2 instance type (ex: t3.micro or t3.medium)'
        required: true
        default: 'c6a.4xlarge'
      EC2_TARGET_SIZE:
        description: Storage allocated to the machine (in GB)
        required: true
        type: string
        default: '30'
      EXPERIMENT_ID:
        description: Experiment ID (to identify the run in S3)
        required: true
        type: string
      PIPELINE:
        description: Pipeline to run
        required: true
        default: main
permissions: write-all
concurrency: 
  # Only one workflow run is allowed to run at a time in the repository
  group: ${{ github.repository }}
  cancel-in-progress: true
jobs:
  main:
    if: github.event.inputs.PIPELINE == 'main'
    uses: ./.github/workflows/main.yaml
    with:
      EC2_INSTANCE_TYPE: ${{ github.event.inputs.EC2_INSTANCE_TYPE }}
      EC2_TARGET_SIZE: ${{ github.event.inputs.EC2_TARGET_SIZE }}
      EXPERIMENT_ID: ${{ github.event.inputs.EXPERIMENT_ID }}
    secrets:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
